# Generated by Django 3.2.9 on 2021-11-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=10)),
                ('pic_url', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
