# Generated by Django 3.2.9 on 2021-11-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookname',
            new_name='book_name',
        ),
    ]
