# Generated by Django 3.2.9 on 2021-11-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0002_rename_bookname_book_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='bookname',
        ),
    ]
